from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
INPUT_DIR = BASE_DIR / "input"
OUTPUT_DIR = BASE_DIR / "output" / "boxes"
DEBUG_DIR = OUTPUT_DIR / "_debug"

# Set True to wipe previous box output on each run
CLEAR_OUTPUT = True

# Numbering behavior
GLOBAL_NUMBERING = False
GLOBAL_START = 1
ROW_PAGE_START_QUESTION = {
    "answer_sheet_pg_1": 1,
    "answer_sheet_pg_2": 1,
}
COL_PAGE_START_QUESTION = {
    "paper_pg_1": 1,
    "paper_pg_2": 121,
}

# Shared preprocessing
ADAPTIVE_BLOCK = 31
ADAPTIVE_C = 12
PERSPECTIVE_CORRECTION = True
PERSPECTIVE_DETECT_MAX_DIM = 1600
PERSPECTIVE_MIN_AREA_RATIO = 0.25
PERSPECTIVE_FALLBACK_MIN_AREA_RATIO = 0.35
PERSPECTIVE_APPROX_EPS_RATIO = 0.02
PERSPECTIVE_MAX_ASPECT_RATIO = 2.2
PERSPECTIVE_MAX_ANGLE_COS = 0.45
PERSPECTIVE_MIN_OUTPUT_SIDE = 200
PERSPECTIVE_MIN_DISTORTION_RATIO = 0.20
PERSPECTIVE_WARP_EXPAND_RATIO = 1.05
PERSPECTIVE_MIN_EDGE_SUPPORT = 0.30
PERSPECTIVE_EDGE_SUPPORT_THICKNESS = 7
GRID_ROI_ENABLE = True
GRID_ROI_MIN_INTERSECTION_PIXELS = 200
GRID_ROI_LOW_PCT = 1.0
GRID_ROI_HIGH_PCT = 99.0
GRID_ROI_COMPONENT_DILATE = 5
GRID_ROI_COMPONENT_MIN_BOX_RATIO = 0.05
GRID_ROI_STRONG_ROW_RATIO = 0.30
GRID_ROI_STRONG_TRIM_MIN = 60
GRID_ROI_SECONDARY_ROW_RATIO = 0.22
GRID_ROI_COMPONENT_PAD_X_RATIO = 0.02
GRID_ROI_COMPONENT_PAD_Y_RATIO = 0.025
GRID_ROI_COMPONENT_PAD_X_MIN = 12
GRID_ROI_COMPONENT_PAD_Y_MIN = 12
GRID_ROI_PAD_X_RATIO = 0.055
GRID_ROI_PAD_Y_RATIO = 0.06
GRID_ROI_PAD_X_MIN = 20
GRID_ROI_PAD_Y_MIN = 16
GRID_ROI_MIN_WIDTH_RATIO = 0.45
GRID_ROI_MIN_HEIGHT_RATIO = 0.45
GRID_H_LINE_SCALE = 25
GRID_V_LINE_SCALE = 30
GRID_PERSPECTIVE_ENABLE = True
GRID_PERSPECTIVE_APPROX_EPS_RATIO = 0.02
GRID_PERSPECTIVE_COMPONENT_DILATE = 7
GRID_PERSPECTIVE_MIN_AREA_RATIO = 0.55
GRID_PERSPECTIVE_MIN_DISTORTION_RATIO = 0.08
GRID_PERSPECTIVE_WARP_EXPAND_RATIO = 1.0
GRID_ALIGN_MIN_ANGLE = 0.15
GRID_ALIGN_MAX_ANGLE = 5.0
GRID_ALIGN_RECROP_MIN_WIDTH_RATIO = 0.90
GRID_ALIGN_RECROP_MIN_HEIGHT_RATIO = 0.90
DESKEW = True
DESKEW_MAX_ANGLE = 8.0
DESKEW_GRID_ANGLE_LIMIT = 12.0
DESKEW_FALLBACK_ANGLE_LIMIT = 20.0
DESKEW_MIN_LINE_COUNT = 3
PDF_RENDER_DPI = 200

# Row-layout tuning
ROW_H_LINE_SCALE = 35
ROW_V_LINE_SCALE = 35
ROW_LINE_THRESH_RATIO = 0.15
ROW_VERT_LINE_MIN_HEIGHT_PCT = 0.6
ROW_BAND_MIN_HEIGHT = 20
ROW_BAND_MAX_HEIGHT = 60
ROW_MIN_BAND_INK = 250
ROW_IGNORE_TOP_PCT = 0.08
ROW_LOCAL_MIN_SPAN_WIDTH = 20
ROW_LOCAL_BAND_MAX_HEIGHT = 160
ROW_LOCAL_MIN_BAND_INK = 8
ROW_LOCAL_MIN_INK_DENSITY = 0.008
ROW_LOCAL_HEIGHT_GAP_MIN = 12
ROW_LOCAL_HEIGHT_RATIO_MIN = 1.45
ROW_LOCAL_CLUSTER_TOL_MIN = 18
ROW_LOCAL_CLUSTER_TOL_RATIO = 0.35
ROW_LOCAL_MIN_SPANS = 8
ROW_LOCAL_MIN_SUPPORT = 3
ROW_LOCAL_MIN_SUPPORT_RATIO = 0.40
ROW_MAX_LAYOUT_ROWS = 8
ROW_MIN_LAYOUT_COLS = 10
ROW_PAD_X = 2
ROW_PAD_Y = 0
ROW_BAND_PAD_TOP = 3
ROW_BAND_PAD_BOTTOM = 3

# Column-layout tuning
COL_H_LINE_SCALE = GRID_H_LINE_SCALE
COL_V_LINE_SCALE = GRID_V_LINE_SCALE
COL_ROW_LINE_THRESH_RATIO = 0.08
COL_MIN_LINE_RUN_WIDTH = 2
COL_BAND_MIN_HEIGHT = 20
COL_BAND_MAX_HEIGHT = 70
COL_MIN_BAND_INK = 200
COL_IGNORE_TOP_PCT = 0.02
COL_PAD_X = 2
COL_PAD_Y = 0
COL_BAND_PAD_TOP = 2
COL_BAND_PAD_BOTTOM = 2
EXPECTED_ROWS = 30
EXPECTED_ANSWER_COLS = 4
MIN_ANSWER_X_FRAC = 0.20
WIDEST_BANDS_KEEP = 4
COL_SPLIT_COMPONENT_MAX_RATIO = 0.75
COL_SPLIT_COMBINED_MIN_RATIO = 0.85
COL_SPLIT_COMBINED_MAX_RATIO = 1.35

# Auto-detection tuning
ROW_GAP_CV_MAX = 0.18
ROW_GAP_CLOSE_TOL_PCT = 0.25
ROW_GAP_CLOSE_TOL_MIN = 3
ROW_MIN_UNIFORM_GAP_RATIO = 0.75
ROW_MIN_MATCHED_ROW_RATIO = 0.75
MIN_COL_LAYOUT_ANSWER_BANDS = 2
MIN_COL_LAYOUT_ROWS = 10


__all__ = [name for name in globals() if name.isupper()]
